// Copyright (C) 2022, Savoir-faire Linux (https://www.savoirfairelinux.com)
// SPDX-License-Identifier: CC-BY-4.0

:pdf-theme: themes/theme.yml
:doctype: book

Test report
===========
:toc:
:icons:
:iconsdir: ./doc/icons/
:sectnumlevels: 1

include::include/test-reports.adoc[]
include::include/latency-test-reports.adoc[]

== About this documentation

This documentation uses the AsciiDoc documentation generator. It is a convenient
format that allows using plain-text formatted writing that can later be
converted to various output formats such as HTML and PDF.

In order to generate an HTML version of this documentation, use the following
command (the asciidoc package will need to be installed in your Linux
distribution):

  $ asciidoc main.adoc

This will result in a README.html file being generated in the current directory.

If you prefer a PDF version of the documentation instead, use the following
command (the dblatex package will need to be installed on your Linux
distribution):

  $ asciidoctor-pdf main.adoc
